# This is a basic workflow to help you get started with Actions

name: corne

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags: 
      - '*'
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Prerequisites
        run: sudo apt-get update && sudo apt-get install -y git python3-pip python3-setuptools tree
      # Runs a set of commands using the runners shell
      - name: install qmk cli
        run: python3 -m pip install --user qmk        
      - name: chmod 
        run: chmod +x $HOME/.local/bin/qmk
      - name: Setup QMK CLI
        run: |
          $HOME/.local/bin/qmk setup -H $(pwd)/qmk_firmware -y
          SB_LOCAL_PATH=$(pwd)
          echo $SB_LOCAL_PATH
          ln -s $(pwd)/panda $(pwd)/qmk_firmware/keyboards/crkbd/rev1/common/keymaps/panda
          $HOME/.local/bin/qmk config user.keyboard=crkbd/rev1/common
          $HOME/.local/bin/qmk config user.keymap=panda
          $HOME/.local/bin/qmk json2c configurator/panda_corne_crab_punch.json > generated_keymap.c
          cat panda/keymap.c >> generated_keymap.c
          rm panda/keymap.c
          mv generated_keymap.c panda/keymap.c
          $HOME/.local/bin/qmk compile
      - uses: actions/upload-artifact@v2
        with:
          name: corne-panda-default.hex
          path: qmk_firmware/crkbd_rev1_common_panda.hex
      - name: Release
        uses: docker://softprops/action-gh-release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: qmk_firmware/crkbd_rev1_common_panda.hex
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
